config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :workouts
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post "login", to: 'sessions#create'
  delete "logout", to: 'sessions#destroy'
  get 'search', to: 'workouts#search'
  resources :difficulties, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/difficulty.rb
class Difficulty < ApplicationRecord
  validates :name, presence: true, length: { minimum: 4, maximum: 20}
  validates_uniqueness_of :name
end

app/models/difficulty.rb
class Difficulty < ApplicationRecord
  has_many :workout_difficulties
  has_many :workouts, through: :workout_difficulties

  validates :name, presence: true, length: { minimum: 4, maximum: 20}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  has_many :workouts, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false}, length: {minimum:3, maximum:15}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false},length: {maximum:110}, format: { with: VALID_EMAIL_REGEX}
  has_secure_password #Might have to remove this unsure what doing
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :workout_difficulties
  has_many :difficulties, through: :workout_difficulties
  #Validation code for DB entries
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/models/workout_difficulty.rb
class WorkoutDifficulty < ApplicationRecord
  belongs_to :workout
  belongs_to :difficulty
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/difficulties_controller.rb
class DifficultiesController < ApplicationController
before_action :require_admin, except: [:index, :show]

   def new
     @difficulty = Difficulty.new
   end

   def create
     @difficulty = Difficulty.new(difficulty_params)
     if @difficulty.save
       flash[:notice] = "Difficulty was successfully created"
       redirect_to @difficulty
     else
       render 'new'
     end
   end

   def edit
     @difficulty = Difficulty.find(params[:id])
   end

   def update
     @difficulty = Difficulty.find(params[:id])
     if @difficulty.update(difficulty_params)
       flash[:notice] = "Updated successfully"
       redirect_to @difficulty
     else
       render 'edit'
     end
   end


   def index
     @difficulties = Difficulty.all
   end

   def show
     @difficulty = Difficulty.find(params[:id])
     @workouts = @difficulty.workouts.paginate(page: params[:page], per_page: 3)
   end

   private

   def difficulty_params
    params.require(:difficulty).permit(:name)
   end

   def require_admin
     if !(logged_in? && current_user.admin?)
       flash[:alert] = "Only admins can perform that action"
       redirect_to difficulties_path
     end
   end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to workouts_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:notice] = "Log in was succesful"
    redirect_to user
  else
    flash.now[:alert] = "There was something wrong with the credentials you have entered"
    render 'new'
  end
end

def destroy
  session[:user_id] = nil
  flash[:notice] = "Logged out"
  redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @workouts = @user.workouts.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users  = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Congratulations #{@user.username} on joining the HomeFitness family!!! You have successfully created and account"
      redirect_to workouts_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all workouts have been deleted"
    redirect_to workouts_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @workouts  = Workout.paginate(page: params[:page], per_page: 5)
  end

  def new
    @workout = Workout.new
  end

  def edit
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user = current_user
    if @workout.save
      flash[:notice] = "Workout was created successfully"
      redirect_to @workout
    else
      render 'new'
    end
  end

  def update
    if @workout.update(workout_params)
      flash[:notice] = "Workout was updated successfully"
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to workouts_path
  end

  def search
    @workouts = Workout.where("title LIKE ?", "%" + params[:q] + "%")
  end

  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:title, :description, difficulty_ids: [])
  end

  def require_same_user
    if current_user != @workout.user && !current_user.admin
      flash[:alert] = "You can only edit or delete your own workout"
      redirect_to @workout
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt:user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/difficulties/_difficulty.html.erb
<%= link_to difficulty.name, difficulty_path(difficulty), class:"badge badge-info" %>

app/views/difficulties/_form.html.erb
<%= render 'shared/errors', obj: @difficulty%>
<%= form_with(model: @difficulty, class: "shadow p-3 mb-3 bg-info rounded ",local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Difficulty ", class: "col-2 col-form-label text-dark" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter difficulty" %>
    </div>
  </div>
  <div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-outline-dark btn-lg" %>
  </div>
<% end %>

app/views/difficulties/edit.html.erb
<h1 class="text-center mt-4">Edit Difficulty Name</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to difficulty page ]', difficulty_path(@difficulty), class: "text-info" %>
    </div>
  </div>
</div>

app/views/difficulties/index.html.erb
<h1 class="text-center mt-4">Difficulties</h1>

<div class="container">
  <% @difficulties.each do |difficulty| %>
  <div class="row justify-content-md-center">
    <div class="col-4 mt-4">
      <div class="card text-center shadow mb-5 bg-info rounded">
        <div class="card-body">
          <h5 class="card-title"><%= link_to difficulty.name, difficulty_path(difficulty), class: "text-white"%></h5>
          <p class="card-text"><%= pluralize(difficulty.workouts.count, "workout") %></p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/difficulties/new.html.erb
<h1 class="text-center mt-4">Create a new Difficulty</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @difficulty%>
      <%= form_with(model: @difficulty, class: "shadow p-3 mb-3 bg-info rounded ",local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Difficulty ", class: "col-2 col-form-label text-dark" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter difficulty" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-dark btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to workout listing ]', workouts_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/difficulties/show.html.erb
<h1 class="text-center mt-4">Difficulty: <%= @difficulty.name %></h1>

  <% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit difficulty name", edit_difficulty_path(@difficulty), class: "btn btn-outline-info" %>
  </div>
  <% end %>

<h3 class="text-center mt-4">Workouts</h3>

<div class="flickr_pagination">
  <%= will_paginate @workouts, :container => false %>
</div>

<%= render 'workouts/workout' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @workouts, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
   <div class="container text-center">
     <small>Copyright &copy; Andrew Hayward</small>
   </div>
 </footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>  alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home Fitness", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Workouts
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new Workout", new_workout_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View Workouts", workouts_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Difficulty
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin?%>
            <%= link_to "Create new Difficulty", new_difficulty_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View Difficulties", difficulties_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?"} %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="/search">
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search for workout" aria-label="Search">
      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalYearProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Workout listing', workouts_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white ">
      <h1 class="display-4">Home Fitness</h1>
      <p class="lead">Welcome, you have found our page that is dedicated into helping you get a better life style</p>
      <hr class="my-4">
      <p>This website allows you to get a great workout from the comfort of your own home, our workouts are free and have been created just for you. Use the button below to sign up and start getting fit now!!!</p>
      <%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-info" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user%>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded ",local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-dark" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-dark" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address"%>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-dark" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password"%>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-dark btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to workout listing ]', workouts_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.workouts.count, "workout") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-primary"%>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete User", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete this user and all workouts associated"}%>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Home Fitness</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
<div class="text-center mt-4">
  <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
</div>
<% end %>

<h3 class="text-center mt-4">Workouts</h3>

<div class="flickr_pagination">
  <%= will_paginate @workouts, :container => false %>
</div>

<%= render 'workouts/workout' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @workouts, :container => false %>
</div>

app/views/workouts/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @workout %>
      <%= form_with(model: @workout, class: "shadow p-3 mb-3 bg-info rounded ",local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-dark" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of Workout" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-dark" %>
          <div class="col-10">
            <%= f.text_area :description , rows:10, class: "form-control shadow rounded", placeholder: "Desciption of Workout"%>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :difficulty, class: "col-2 col-form-label text-dark" %>
          <div class="col-10">
            <%= f.collection_select(:difficulty_ids, Difficulty.all, :id, :name, {prompt: "Make your selection from the list below (can be empty)"}, {multiple: true,size: 3, class: "custom-select shadow rounded"}) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-dark btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to workout listing ]', workouts_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/workouts/_workout.html.erb
<div class="container">
  <% @workouts.each do |workout| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <% if workout.user %>
          by <%= link_to workout.user.username, user_path(workout.user) %>
          <% end %>
          <% if workout.difficulties.any? %>
            <div class="mt-2"><%= render workout.difficulties %></div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to workout.title, workout_path(workout), class:"text-info" %></h5>
          <p class="card-text"><%= truncate(workout.description, length: 100) %></p>
          <%= link_to "View", workout_path(workout), class: "btn btn-outline-success" %>
          <% if logged_in? && (workout.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_workout_path(workout), class: "btn btn-outline-primary"%>
            <%= link_to "Delete", workout_path(workout), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete this workout?"}%>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(workout.created_at) %> ago,
            edited <%= time_ago_in_words(workout.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/workouts/edit.html.erb
<h1 class="text-center mt-4">Edit Workout</h1>
<%= render 'form' %>

app/views/workouts/index.html.erb
<h1 class="text-center mt-4">Listing of all Workouts</h1>

<div class="flickr_pagination">
  <%= will_paginate @workouts, :container => false %>
</div>
<%= render 'workout' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @workouts, :container => false %>
</div>

app/views/workouts/new.html.erb
<h1 class="text-center mt-4">Create a New Workout</h1>
<%= render 'form' %>

app/views/workouts/search.html.erb
<h1 class="text-center mt-4">Search Results</h1>

<%= render 'workout' %>

<div class="mb-3 row justify-content-center">
  <%= link_to '[ Return to Workout list ]', workouts_path, class: "text-info" %>
</div>

app/views/workouts/show.html.erb
<h2 class="text-center mt-4"><%= @workout.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @workout.user.username %>
          <%= link_to gravatar_for(@workout.user), user_path(@workout.user) %>
          <% if @workout.difficulties.any? %>
            <div class="mt-2"><%= render @workout.difficulties %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><td><%= simple_format(@workout.description) %></div>
            <% if logged_in? && (@workout.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_workout_path(@workout), class: "btn btn-outline-primary"%>
              <%= link_to "Delete", workout_path(@workout), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete this workout?"}%>
            <% end %>
      </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@workout.created_at) %> ago,
            edited <%= time_ago_in_words(@workout.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mb-3 row justify-content-center">
  <%= link_to '[ Return to Users List ]',  users_path, class: "text-info" %>
</div>